### PR TITLE
Fix found bugs

### PR DESCRIPTION
**Pull request by hvostya**
tfs#107753

### CODE REVIEW

**Comment by ehaberev** [comment]
Do we have a corresponding task for generator?

**Comment by hvostya** [comment]
What for should we have task?
There is a task as soon as I know to create mechanism to allow applied oriented programmers override base edit form logic. Used variant is one of possible but not mixin one.

**Comment by ehaberev** [comment]
So would we like to use BaseEditFormRoute only in dummy application?
I mean application developers will encounter the same problem as i understood.
If you would like to create mixin to solve this problem may be we could do it in this pull request directly?

**Comment by hvostya** [comment]
It is just a part of task tfs#107753.
Task was taken to resolve if it is addon or dummy problem. Now it is on support team. I'll add your comments on task not to forget about mixin and generator.

**Comment by ehaberev** [comment]
Ok, i see. Thanks.

**Pull request merged**
