### PR TITLE
Fix flexberry-core blueprints

### PR DESCRIPTION
**Pull request by KollegOFF**
[TFS#106113](http://dis-tfs:8080/Common/Flex/_workitems?_a=edit&id=106113).

### CODE REVIEW

**Comment by ehaberev** [comment]
Please fix [unit test](https://travis-ci.org/Flexberry/ember-flexberry/jobs/134738937#L1054)

**Comment by ehaberev** [comment]
I guess I was fixed this test in [this commit](https://github.com/Flexberry/ember-flexberry/commit/6c343e49f7418a457d1039dde143b3a2a3460a89). Please copy modifications of `reload-list-mixin.js` into your branch.

**Comment by KollegOFF** [comment]
I will merge 'develop' into 'fix-generator-delete-dependencies', ok?

**Comment by ehaberev** [comment]
Ok, you can merge develop branch into your branch.

**Pull request merged**
